/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dnnctlskyqcuibvwtsfm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRubmN0bHNreXFjdWlidnd0c2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0OTI3NTcsImV4cCI6MjA3NTA2ODc1N30.o_Fa8Piuvipk9eP-MLpV-YJKTdmEElL5yGdMAvOYVjI"