{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b64c7fdf-7c4b-4865-90b5-ce70792c02bd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: python-dotenv in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.1.1)\n",
      "Collecting supabase\n",
      "  Downloading supabase-2.27.2-py3-none-any.whl.metadata (4.6 kB)\n",
      "Requirement already satisfied: psycopg2-binary in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.9.11)\n",
      "Collecting google-generativeai\n",
      "  Using cached google_generativeai-0.8.6-py3-none-any.whl.metadata (3.9 kB)\n",
      "Collecting realtime==2.27.2 (from supabase)\n",
      "  Downloading realtime-2.27.2-py3-none-any.whl.metadata (7.0 kB)\n",
      "Collecting supabase-functions==2.27.2 (from supabase)\n",
      "  Downloading supabase_functions-2.27.2-py3-none-any.whl.metadata (2.4 kB)\n",
      "Collecting storage3==2.27.2 (from supabase)\n",
      "  Downloading storage3-2.27.2-py3-none-any.whl.metadata (2.1 kB)\n",
      "Collecting supabase-auth==2.27.2 (from supabase)\n",
      "  Downloading supabase_auth-2.27.2-py3-none-any.whl.metadata (6.4 kB)\n",
      "Collecting postgrest==2.27.2 (from supabase)\n",
      "  Downloading postgrest-2.27.2-py3-none-any.whl.metadata (3.4 kB)\n",
      "Requirement already satisfied: httpx<0.29,>=0.26 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from supabase) (0.28.1)\n",
      "Collecting yarl>=1.22.0 (from supabase)\n",
      "  Downloading yarl-1.22.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (75 kB)\n",
      "Collecting deprecation>=2.1.0 (from postgrest==2.27.2->supabase)\n",
      "  Using cached deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)\n",
      "Requirement already satisfied: pydantic<3.0,>=1.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from postgrest==2.27.2->supabase) (2.11.7)\n",
      "Requirement already satisfied: typing-extensions>=4.14.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from realtime==2.27.2->supabase) (4.14.0)\n",
      "Requirement already satisfied: websockets<16,>=11 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from realtime==2.27.2->supabase) (15.0.1)\n",
      "Collecting pyiceberg>=0.10.0 (from storage3==2.27.2->supabase)\n",
      "  Downloading pyiceberg-0.10.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (4.9 kB)\n",
      "Collecting pyjwt>=2.10.1 (from pyjwt[crypto]>=2.10.1->supabase-auth==2.27.2->supabase)\n",
      "  Using cached PyJWT-2.10.1-py3-none-any.whl.metadata (4.0 kB)\n",
      "Collecting strenum>=0.4.15 (from supabase-functions==2.27.2->supabase)\n",
      "  Using cached StrEnum-0.4.15-py3-none-any.whl.metadata (5.3 kB)\n",
      "Requirement already satisfied: anyio in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpx<0.29,>=0.26->supabase) (4.9.0)\n",
      "Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpx<0.29,>=0.26->supabase) (2024.2.2)\n",
      "Requirement already satisfied: httpcore==1.* in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpx<0.29,>=0.26->supabase) (1.0.5)\n",
      "Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpx<0.29,>=0.26->supabase) (2.10)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpcore==1.*->httpx<0.29,>=0.26->supabase) (0.14.0)\n",
      "Collecting h2<5,>=3 (from httpx[http2]<0.29,>=0.26->postgrest==2.27.2->supabase)\n",
      "  Using cached h2-4.3.0-py3-none-any.whl.metadata (5.1 kB)\n",
      "Collecting hyperframe<7,>=6.1 (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.27.2->supabase)\n",
      "  Using cached hyperframe-6.1.0-py3-none-any.whl.metadata (4.3 kB)\n",
      "Collecting hpack<5,>=4.1 (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.27.2->supabase)\n",
      "  Using cached hpack-4.1.0-py3-none-any.whl.metadata (4.6 kB)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic<3.0,>=1.9->postgrest==2.27.2->supabase) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.33.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic<3.0,>=1.9->postgrest==2.27.2->supabase) (2.33.2)\n",
      "Requirement already satisfied: typing-inspection>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic<3.0,>=1.9->postgrest==2.27.2->supabase) (0.4.1)\n",
      "Collecting google-ai-generativelanguage==0.6.15 (from google-generativeai)\n",
      "  Using cached google_ai_generativelanguage-0.6.15-py3-none-any.whl.metadata (5.7 kB)\n",
      "Requirement already satisfied: google-api-core in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-generativeai) (2.19.1)\n",
      "Requirement already satisfied: google-api-python-client in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-generativeai) (2.154.0)\n",
      "Requirement already satisfied: google-auth>=2.15.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-generativeai) (2.31.0)\n",
      "Requirement already satisfied: protobuf in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-generativeai) (5.29.5)\n",
      "Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-generativeai) (4.66.2)\n",
      "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.24.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-api-core->google-generativeai) (1.63.2)\n",
      "Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-api-core->google-generativeai) (2.31.0)\n",
      "Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.64.1)\n",
      "Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.62.2)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-auth>=2.15.0->google-generativeai) (5.3.3)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-auth>=2.15.0->google-generativeai) (4.9)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (3.3.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2.2.1)\n",
      "Requirement already satisfied: pyasn1>=0.1.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rsa<5,>=3.1.4->google-auth>=2.15.0->google-generativeai) (0.6.0)\n",
      "Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from deprecation>=2.1.0->postgrest==2.27.2->supabase) (23.2)\n",
      "Collecting cachetools<6.0,>=2.0.0 (from google-auth>=2.15.0->google-generativeai)\n",
      "  Using cached cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)\n",
      "Requirement already satisfied: click<9.0.0,>=7.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyiceberg>=0.10.0->storage3==2.27.2->supabase) (8.1.7)\n",
      "Requirement already satisfied: fsspec>=2023.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyiceberg>=0.10.0->storage3==2.27.2->supabase) (2024.5.0)\n",
      "Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyiceberg>=0.10.0->storage3==2.27.2->supabase) (5.1.0)\n",
      "Requirement already satisfied: pyparsing<4.0.0,>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyiceberg>=0.10.0->storage3==2.27.2->supabase) (3.1.2)\n",
      "Collecting pyroaring<2.0.0,>=1.0.0 (from pyiceberg>=0.10.0->storage3==2.27.2->supabase)\n",
      "  Downloading pyroaring-1.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (10 kB)\n",
      "Requirement already satisfied: rich<15.0.0,>=10.11.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyiceberg>=0.10.0->storage3==2.27.2->supabase) (14.2.0)\n",
      "Requirement already satisfied: sortedcontainers==2.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyiceberg>=0.10.0->storage3==2.27.2->supabase) (2.4.0)\n",
      "Collecting strictyaml<2.0.0,>=1.7.0 (from pyiceberg>=0.10.0->storage3==2.27.2->supabase)\n",
      "  Using cached strictyaml-1.7.3-py3-none-any.whl.metadata (11 kB)\n",
      "Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyiceberg>=0.10.0->storage3==2.27.2->supabase) (8.2.3)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.27.2->supabase) (3.0.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.27.2->supabase) (2.17.2)\n",
      "Requirement already satisfied: python-dateutil>=2.6.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from strictyaml<2.0.0,>=1.7.0->pyiceberg>=0.10.0->storage3==2.27.2->supabase) (2.9.0.post0)\n",
      "Requirement already satisfied: mdurl~=0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.27.2->supabase) (0.1.2)\n",
      "Requirement already satisfied: cryptography>=3.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyjwt[crypto]>=2.10.1->supabase-auth==2.27.2->supabase) (44.0.0)\n",
      "Requirement already satisfied: cffi>=1.12 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->supabase-auth==2.27.2->supabase) (1.16.0)\n",
      "Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->supabase-auth==2.27.2->supabase) (2.21)\n",
      "Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.6.0->strictyaml<2.0.0,>=1.7.0->pyiceberg>=0.10.0->storage3==2.27.2->supabase) (1.16.0)\n",
      "Requirement already satisfied: multidict>=4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from yarl>=1.22.0->supabase) (6.0.5)\n",
      "Collecting propcache>=0.2.1 (from yarl>=1.22.0->supabase)\n",
      "  Downloading propcache-0.4.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (13 kB)\n",
      "Requirement already satisfied: sniffio>=1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anyio->httpx<0.29,>=0.26->supabase) (1.3.1)\n",
      "Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-api-python-client->google-generativeai) (0.22.0)\n",
      "Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-api-python-client->google-generativeai) (0.2.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from google-api-python-client->google-generativeai) (4.1.1)\n",
      "Downloading supabase-2.27.2-py3-none-any.whl (16 kB)\n",
      "Downloading postgrest-2.27.2-py3-none-any.whl (21 kB)\n",
      "Downloading realtime-2.27.2-py3-none-any.whl (22 kB)\n",
      "Downloading storage3-2.27.2-py3-none-any.whl (27 kB)\n",
      "Downloading supabase_auth-2.27.2-py3-none-any.whl (48 kB)\n",
      "Downloading supabase_functions-2.27.2-py3-none-any.whl (8.5 kB)\n",
      "Using cached h2-4.3.0-py3-none-any.whl (61 kB)\n",
      "Using cached hpack-4.1.0-py3-none-any.whl (34 kB)\n",
      "Using cached hyperframe-6.1.0-py3-none-any.whl (13 kB)\n",
      "Using cached google_generativeai-0.8.6-py3-none-any.whl (155 kB)\n",
      "Using cached google_ai_generativelanguage-0.6.15-py3-none-any.whl (1.3 MB)\n",
      "Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)\n",
      "Downloading pyiceberg-0.10.0-cp311-cp311-macosx_11_0_arm64.whl (587 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m587.0/587.0 kB\u001b[0m \u001b[31m11.5 MB/s\u001b[0m  \u001b[33m0:00:00\u001b[0m\n",
      "\u001b[?25hUsing cached cachetools-5.5.2-py3-none-any.whl (10 kB)\n",
      "Downloading pyroaring-1.0.3-cp311-cp311-macosx_11_0_arm64.whl (313 kB)\n",
      "Using cached strictyaml-1.7.3-py3-none-any.whl (123 kB)\n",
      "Using cached PyJWT-2.10.1-py3-none-any.whl (22 kB)\n",
      "Using cached StrEnum-0.4.15-py3-none-any.whl (8.9 kB)\n",
      "Downloading yarl-1.22.0-cp311-cp311-macosx_11_0_arm64.whl (94 kB)\n",
      "Downloading propcache-0.4.1-cp311-cp311-macosx_11_0_arm64.whl (47 kB)\n",
      "Installing collected packages: strenum, pyroaring, pyjwt, propcache, hyperframe, hpack, deprecation, cachetools, yarl, strictyaml, h2, realtime, pyiceberg, supabase-functions, supabase-auth, storage3, postgrest, supabase, google-ai-generativelanguage, google-generativeai\n",
      "\u001b[2K  Attempting uninstall: cachetools\n",
      "\u001b[2K    Found existing installation: cachetools 5.3.3\n",
      "\u001b[2K    Uninstalling cachetools-5.3.3:\n",
      "\u001b[2K      Successfully uninstalled cachetools-5.3.3\n",
      "\u001b[2K  Attempting uninstall: yarl\n",
      "\u001b[2K    Found existing installation: yarl 1.9.4━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m 8/20\u001b[0m [yarl]\n",
      "\u001b[2K    Uninstalling yarl-1.9.4:m╺\u001b[0m\u001b[90m━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m 8/20\u001b[0m [yarl]\n",
      "\u001b[2K      Successfully uninstalled yarl-1.9.4━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m 8/20\u001b[0m [yarl]\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m20/20\u001b[0m [google-generativeai]ogle-generativeai]language]\n",
      "\u001b[1A\u001b[2K\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "langchain-experimental 0.3.4 requires langchain-community<0.4.0,>=0.3.0, but you have langchain-community 0.0.20 which is incompatible.\n",
      "langchain-experimental 0.3.4 requires langchain-core<0.4.0,>=0.3.28, but you have langchain-core 0.1.23 which is incompatible.\n",
      "google-cloud-resource-manager 1.12.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 5.29.5 which is incompatible.\n",
      "google-cloud-aiplatform 1.100.0 requires google-cloud-storage<3.0.0,>=1.32.0, but you have google-cloud-storage 3.4.0 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed cachetools-5.5.2 deprecation-2.1.0 google-ai-generativelanguage-0.6.15 google-generativeai-0.8.6 h2-4.3.0 hpack-4.1.0 hyperframe-6.1.0 postgrest-2.27.2 propcache-0.4.1 pyiceberg-0.10.0 pyjwt-2.10.1 pyroaring-1.0.3 realtime-2.27.2 storage3-2.27.2 strenum-0.4.15 strictyaml-1.7.3 supabase-2.27.2 supabase-auth-2.27.2 supabase-functions-2.27.2 yarl-1.22.0\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m25.2\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.3\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install python-dotenv supabase psycopg2-binary google-generativeai"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "14c50422-0956-489f-bec1-0a18397cf9ec",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (25.2)\n",
      "Collecting pip\n",
      "  Using cached pip-25.3-py3-none-any.whl.metadata (4.7 kB)\n",
      "Using cached pip-25.3-py3-none-any.whl (1.8 MB)\n",
      "Installing collected packages: pip\n",
      "  Attempting uninstall: pip\n",
      "    Found existing installation: pip 25.2\n",
      "    Uninstalling pip-25.2:\n",
      "      Successfully uninstalled pip-25.2\n",
      "Successfully installed pip-25.3\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade pip"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "ef27f494-6be0-4c5f-a428-4c8e8acda63b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ 환경 변수 로드 성공: https://gknekrinduyp...\n",
      "🚀 20명 가상 유저 생성 시작...\n",
      "✅ 생성 완료: ㅇ\n",
      "✅ 생성 완료: ㅋㅋㅋ\n",
      "✅ 생성 완료: 중국공산당척결\n",
      "✅ 생성 완료: 해병1244기\n",
      "✅ 생성 완료: 당근\n",
      "✅ 생성 완료: 좌빨배급견\n",
      "✅ 생성 완료: ㅇㅇ\n",
      "✅ 생성 완료: 극우는짖어\n",
      "✅ 생성 완료: 호감고닉게이\n",
      "✅ 생성 완료: ㅉ재매이\n",
      "✅ 생성 완료: 닉네임없\n",
      "✅ 생성 완료: 한뚜껑쥴리둘이\n",
      "✅ 생성 완료: 이거뭐하는사이트임\n",
      "✅ 생성 완료: ㅁㅁㅁㅈ\n",
      "✅ 생성 완료: 이슈ㅈ키\n",
      "✅ 생성 완료: 댓글알바\n",
      "✅ 생성 완료: 꺼무위키\n",
      "✅ 생성 완료: ㄷㅈㅂㅂ\n",
      "✅ 생성 완료: ㅇㅇㅇㅇㅇㅇ\n",
      "✅ 생성 완료: 한남ㅈ\n",
      "\n",
      "✨ 모든 유저 생성 완료 및 ai_personas.json 저장됨.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "from dotenv import load_dotenv\n",
    "from supabase import create_client, Client\n",
    "import json\n",
    "\n",
    "# 1. 환경 변수 로드\n",
    "load_dotenv(dotenv_path='.env.local')\n",
    "\n",
    "url = os.getenv(\"NEXT_PUBLIC_SUPABASE_URL\")\n",
    "key = os.getenv(\"SUPABASE_SERVICE_ROLE_KEY\")\n",
    "supabase: Client = create_client(url, key)\n",
    "\n",
    "\n",
    "# 로드 확인 (보안을 위해 앞부분만 출력)\n",
    "if not url or not key:\n",
    "    print(\"❌ 오류: .env.local 파일에서 정보를 읽어오지 못했습니다. 파일명과 변수명을 확인해주세요.\")\n",
    "else:\n",
    "    print(f\"✅ 환경 변수 로드 성공: {url[:20]}...\")\n",
    "\n",
    "\n",
    "\n",
    "# 2. Supabase 클라이언트 초기화\n",
    "try:\n",
    "    supabase: Client = create_client(url, key)\n",
    "except Exception as e:\n",
    "    print(f\"❌ 클라이언트 초기화 실패: {e}\")\n",
    "\n",
    "\n",
    "\n",
    "# 2. 20명 페르소나 데이터 정의\n",
    "personas_to_create = [\n",
    "    {\"nick\": \"ㅇ\", \"style\": \"분석적, 존댓말\"}, {\"nick\": \"ㅋㅋㅋ\", \"style\": \"정보전달, 공손함\"},\n",
    "    {\"nick\": \"중국공산당척결\", \"style\": \"논리적, 딱딱함\"}, {\"nick\": \"해병1244기\", \"style\": \"직설적, 짧은 반말\"},\n",
    "    {\"nick\": \"당근\", \"style\": \"긍정적, 이모티콘\"}, {\"nick\": \"좌빨배급견\", \"style\": \"공감형, 다정함\"},\n",
    "    {\"nick\": \"ㅇㅇ\", \"style\": \"에너지넘침, 감탄사\"}, {\"nick\": \"극우는짖어\", \"style\": \"감성적, 부드러움\"},\n",
    "    {\"nick\": \"호감고닉게이\", \"style\": \"회의적, 의문문\"}, {\"nick\": \"ㅉ재매이\", \"style\": \"비판적, 냉소적\"},\n",
    "    {\"nick\": \"닉네임없\", \"style\": \"간결함, 까칠함\"}, {\"nick\": \"한뚜껑쥴리둘이\", \"style\": \"민감함, 지적질\"},\n",
    "    {\"nick\": \"이거뭐하는사이트임\", \"style\": \"질문형\"}, {\"nick\": \"ㅁㅁㅁㅈ\", \"style\": \"당황함, 가벼움\"},\n",
    "    {\"nick\": \"이슈ㅈ키\", \"style\": \"엉뚱함, 집요함\"}, {\"nick\": \"댓글알바\", \"style\": \"간절함, 존댓말\"},\n",
    "    {\"nick\": \"꺼무위키\", \"style\": \"방관자, 짧음\"}, {\"nick\": \"ㄷㅈㅂㅂ\", \"style\": \"평범함, 가벼움\"},\n",
    "    {\"nick\": \"ㅇㅇㅇㅇㅇㅇ\", \"style\": \"무심함, 시크함\"}, {\"nick\": \"한남ㅈ\", \"style\": \"짧은 답변, 쿨함\"}\n",
    "]\n",
    "\n",
    "created_ai_list = []\n",
    "\n",
    "print(\"🚀 20명 가상 유저 생성 시작...\")\n",
    "\n",
    "for i, p in enumerate(personas_to_create):\n",
    "    email = f\"ai_bot_{i+1}@gmail.com\" # 가짜 이메일\n",
    "    try:\n",
    "        # Auth 유저 생성\n",
    "        user = supabase.auth.admin.create_user({\n",
    "            \"email\": email,\n",
    "            \"password\": \"password2026!\",\n",
    "            \"user_metadata\": {\"nickname\": p['nick']},\n",
    "            \"email_confirm\": True\n",
    "        })\n",
    "        user_id = user.user.id\n",
    "        \n",
    "        # 정보 저장\n",
    "        created_ai_list.append({\n",
    "            \"user_id\": user_id,\n",
    "            \"nickname\": p['nick'],\n",
    "            \"persona_style\": p['style']\n",
    "        })\n",
    "        print(f\"✅ 생성 완료: {p['nick']}\")\n",
    "    except Exception as e:\n",
    "        print(f\"❌ 실패 ({p['nick']}): {e}\")\n",
    "\n",
    "# 3. 결과를 파일로 저장 (나중에 자동화 스크립트에서 로드해서 사용)\n",
    "with open(\"ai_personas.json\", \"w\", encoding=\"utf-8\") as f:\n",
    "    json.dump(created_ai_list, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "print(\"\\n✨ 모든 유저 생성 완료 및 ai_personas.json 저장됨.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "38329dcf-84d8-4909-95d6-f124b2fdf46c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/w2/cn99zpw14_xgyr6cc03bsxrm0000gn/T/ipykernel_93924/3916659485.py:2: FutureWarning: \n",
      "\n",
      "All support for the `google.generativeai` package has ended. It will no longer be receiving \n",
      "updates or bug fixes. Please switch to the `google.genai` package as soon as possible.\n",
      "See README for more details:\n",
      "\n",
      "https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md\n",
      "\n",
      "  import google.generativeai as genai\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "AI 응답: 쿨하게 한마디로 바꿔달라고 하셨으니, 몇 가지 옵션을 드려볼게요!\n",
      "\n",
      "1.  **왓썹!** (Wassup!)\n",
      "    *   가장 힙하고 많이 쓰이는 표현이죠.\n",
      "\n",
      "2.  **요!** (Yo!)\n",
      "    *   초간단, 초힙! 짧고 강렬합니다.\n",
      "\n",
      "3.  **하이!** (Hi!)\n",
      "    *   가장 기본적인 쿨함이죠. 깔끔하고 직관적.\n",
      "\n",
      "4.  **꾸벅!**\n",
      "    *   인사하는 이모티콘 같은 느낌? 장난스럽고 친근한 쿨함입니다.\n",
      "\n",
      "이 중에 제일 맘에 드는 걸로 골라보세요! 저는 개인적으로 **왓썹!** 이 제일 \"아주 쿨하게\"에 가깝다고 생각합니다. 😉\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import google.genai as genai\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv()\n",
    "genai.configure(api_key=os.getenv(\"GEMINI_API_KEY\"))\n",
    "\n",
    "# 2.0 Flash 모델 사용 (2026년 기준 가장 가성비 좋고 빠름)\n",
    "model = genai.GenerativeModel('gemini-2.5-flash') # 현재 기준 1.5, 곧 2.0 사용 가능\n",
    "\n",
    "response = model.generate_content(\"커뮤니티 댓글처럼 '안녕 하세요'를 아주 쿨하게 한마디로 바꿔줘.\")\n",
    "print(f\"AI 응답: {response.text}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "cd3cb01c-6558-4f77-810f-c53fc6d1ffa6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ 드디어 연결에 성공했습니다!\n",
      "🤖 커뮤니티 자동화 에이전트 가동 시작...\n",
      "[17:41:26] 📌 게시글: 흑백요리사 임성근, 음주운전 3회 고백… '양심선언' 뒤 숨은 진실은?\n",
      "         ㄴ 👤 꺼무위키: 이것도 주작이냐 (조회수 +5)\n",
      "--------------------------------------------------\n",
      "💤 119초간 대기 후 다음 활동...\n",
      "[17:43:37] 📌 게시글: \"쿠폰 뿌려도 소용없었다\"… '청년 사장' 사라진 자영업 잔혹사\n",
      "         ㄴ 👤 꺼무위키: 민생쿠폰? 어림도 없지. 걍 망하는거임. (조회수 +7)\n",
      "--------------------------------------------------\n",
      "💤 95초간 대기 후 다음 활동...\n",
      "[17:45:17] 📌 게시글: 흑백요리사 임성근, 음주운전 3회 고백… '양심선언' 뒤 숨은 진실은?\n",
      "         ㄴ 👤 ㅁㅁㅁㅈ: 아니 임짱이 음주운전을 3번이나 했다고?ㅋㅋㅋㅋㅋ 개당황스럽네 (조회수 +5)\n",
      "--------------------------------------------------\n",
      "💤 100초간 대기 후 다음 활동...\n",
      "[17:47:07] 📌 게시글: \"로봇 단 1대도 못 들어온다\"..현대차 노조, 휴머노이드 '아틀라스'에 선전포고\n",
      "\n",
      "         ㄴ 👤 극우는짖어: 하.. 정말 답답하네. 이러니 우리나라 경쟁력이 떨어지는거 아닌가... 우리 모두를 위해서 좀 더 큰 그림을 봐야 할텐데 말이야.. (조회수 +2)\n",
      "--------------------------------------------------\n",
      "💤 53초간 대기 후 다음 활동...\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[23], line 199\u001b[0m\n\u001b[1;32m    197\u001b[0m wait \u001b[38;5;241m=\u001b[39m random\u001b[38;5;241m.\u001b[39mrandint(\u001b[38;5;241m30\u001b[39m, \u001b[38;5;241m120\u001b[39m)\n\u001b[1;32m    198\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m💤 \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mwait\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m초간 대기 후 다음 활동...\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m--> 199\u001b[0m \u001b[43mtime\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msleep\u001b[49m\u001b[43m(\u001b[49m\u001b[43mwait\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "import os\n",
    "import json\n",
    "import random\n",
    "import time\n",
    "import requests\n",
    "import psycopg2\n",
    "from datetime import datetime\n",
    "from psycopg2.extras import RealDictCursor\n",
    "import google.generativeai as genai\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv(dotenv_path='.env.local')\n",
    "\n",
    "# Gemini 설정\n",
    "genai.configure(api_key=os.getenv(\"GEMINI_API_KEY\"))\n",
    "model = genai.GenerativeModel('gemini-2.5-flash')\n",
    "\n",
    "# 페르소나 로드\n",
    "with open(\"ai_personas.json\", \"r\", encoding=\"utf-8\") as f:\n",
    "    AI_PERSONAS = json.load(f)\n",
    "\n",
    "# 환경 변수 로드\n",
    "\n",
    "def get_db_connection():\n",
    "    # 개별 파라미터로 연결 (가장 안정적)\n",
    "    return psycopg2.connect(\n",
    "        user=os.getenv(\"DB_USER\"),\n",
    "        password=os.getenv(\"DB_PASSWORD\"),\n",
    "        host=os.getenv(\"DB_HOST\"),\n",
    "        port=os.getenv(\"DB_PORT\"),\n",
    "        dbname=os.getenv(\"DB_NAME\"),\n",
    "        cursor_factory=RealDictCursor\n",
    "    )\n",
    "\n",
    "# 연결 테스트\n",
    "try:\n",
    "    conn = get_db_connection()\n",
    "    print(\"✅ 드디어 연결에 성공했습니다!\")\n",
    "    conn.close()\n",
    "except Exception as e:\n",
    "    print(f\"❌ 여전히 오류 발생: {e}\")\n",
    "\n",
    "# def get_db_connection():\n",
    "#     return psycopg2.connect(\n",
    "#         host=DB_HOST, database=DB_NAME, user=DB_USER, password=DB_PASSWORD, port=DB_PORT,\n",
    "#         cursor_factory=RealDictCursor\n",
    "#     )\n",
    "\n",
    "def run_automation_step():\n",
    "    conn = get_db_connection()\n",
    "    cur = conn.cursor()\n",
    "    \n",
    "    try:\n",
    "        # (1) 대상 게시글 무작위 선정 (활성 상태인 것 중 하나)\n",
    "        cur.execute(\"SELECT id, title, preview, thumbnail, view_count FROM public.issues WHERE status = 'active' ORDER BY RANDOM() LIMIT 1\")\n",
    "        issue = cur.fetchone()\n",
    "        if not issue: \n",
    "            print(\"활동할 게시글이 없습니다.\")\n",
    "            return\n",
    "\n",
    "        # (2) 조회수 업데이트 (비정기 규칙: 한 번에 2~7회 상승)\n",
    "        new_views = random.randint(2, 7)\n",
    "        cur.execute(\"UPDATE public.issues SET view_count = view_count + %s WHERE id = %s\", (new_views, issue['id']))\n",
    "\n",
    "        # 3. 썸네일 URL 파싱 로직 (중요!)\n",
    "        # [{\"thumbnail\": \"url\"}] 형태 대응\n",
    "        actual_img_url = None\n",
    "        if issue['thumbnail']:\n",
    "            try:\n",
    "                # 텍스트가 JSON 형태인 경우 파싱\n",
    "                thumb_data = json.loads(issue['thumbnail'])\n",
    "                if isinstance(thumb_data, list) and len(thumb_data) > 0:\n",
    "                    actual_img_url = thumb_data[0].get('thumbnail')\n",
    "                else:\n",
    "                    actual_img_url = issue['thumbnail'] # 그냥 URL인 경우\n",
    "            except:\n",
    "                actual_img_url = issue['thumbnail']\n",
    "                \n",
    "        \n",
    "        # (4) 페르소나 선택\n",
    "        persona = random.choice(AI_PERSONAS)\n",
    "        \n",
    "        # (5) 기존 댓글 맥락 가져오기 (대화 형성용)\n",
    "        cur.execute(\"SELECT user_nick, body FROM public.comments WHERE issue_id = %s ORDER BY created_at DESC LIMIT 3\", (issue['id'],))\n",
    "        prev_comments = cur.fetchall()\n",
    "        context = \"\\n\".join([f\"{c['user_nick']}: {c['body']}\" for c in prev_comments])\n",
    "\n",
    "        # (5) Gemini를 이용한 댓글 생성 (이미지 포함)\n",
    "        prompt = f\"\"\"\n",
    "        너는 커뮤니티 유저 '{persona['nickname']}'이야. \n",
    "        성격/말투: {persona['persona_style']}\n",
    "\n",
    "\n",
    "        [참고할 실제 커뮤니티 댓글 스타일]\n",
    "        - \"저게 가능함?\"\n",
    "        - \"ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ\"\n",
    "        - \"주작이잖아 ㅅㅂ\"\n",
    "        - \"인증해\"\n",
    "        - \"걍 그렇네.. 난 별로인듯\"\n",
    "        - \"오 정보 감사요\"\n",
    "        - \"미쳤네\"\n",
    "        - \"이거 3년 전에도 비슷한 사건 있었음\"\n",
    "        - \"나라가 왜 이 모양인가… 책임질 놈들은 다 도망가고\"\n",
    "        - \"~~ 때문에 나라가 망한다\"\n",
    "        - \"지들 이익만 챙기네\"\n",
    "        - \"법과 질서를 바로 세워야 한다\"\n",
    "        - \"대한민국부터 챙기자...\"\n",
    "        - \"눈치 보느라 할 말도 못 하네 에휴\"\n",
    "        - \"범죄자들 다 처벌해라\"\n",
    "        - \"외국인 먼저 챙겨주는 정부 믿을 수 있냐\"\n",
    "        - \"이런 게 진짜 매국노지 ㅋㅋㅋ\"\n",
    "        - \"자주국방 강화해야 한다\"\n",
    "        - \"이 새끼들은 반역자야\"\n",
    "        - \"공정이 어디 있어? 요즘 세상.\"\n",
    "        - \"윤가야 특정 집단만 보호해주는 게 정의냐\"\n",
    "        - \"국가 정체성이 먼저다\"\n",
    "        - \"다들 정신 차려야 한다\"\n",
    "        - \"요새 언론이 편향 보도 너무 심하다. 이게 중국 아니면 뭐냐\"\n",
    "        - \"이래서 보수 지지율이 올라갈 수 밖에 없는거다 이 좌좀 좌빨 배급견들아\"\n",
    "        - \"좌파 언론 믿는 게 웃긴 일이지\"\n",
    "        - \"우리 아이들 안전이 우선이지요\"\n",
    "        - \"나라를 팔아먹는 정책만 하는거지 진짜 답답하다 ㅅㅂ\"\n",
    "        - \"한심한놈들ㅉㅉ\"\n",
    "        - \"이게나라냐????\"\n",
    "        - \"지금정부가 추진하는 정첵은 너무 안이하게 나라를 운영하러는 것같고, 안보떔에 국민들불안만 키우고 있다봅니다\"\n",
    "        - \"ㅋㅋㅋ 매번 이런식으로 두루뭉술하게 넘어가니까 똑같은일 계속 터지는거임. 책임질놈 하나 없고 국민만 호구됨\"\n",
    "        - \"금리 동결이라는데 체감은 전혀 모르겠고 ㅋㅋ 마트 한번 가보면 답 나옴. 기사만 보면 경제 좋아진줄 알겠다\"\n",
    "        - \"부동산 기사마다 안정이라는데 내 주변 집산사람 한명도없음\"\n",
    "        - \"맞긴 한데 이 정도로 욕먹을 일인지는 모르겠음. 연예인도 사람임\"\n",
    "        - \"이해는 가는데 더 극단적으로 갈까봐 걱정됨\"\n",
    "        \n",
    "        \n",
    "        게시글 제목: {issue['title']}\n",
    "        게시글 요약: {issue['preview']}\n",
    "        최근 대화내용:\n",
    "        {context}\n",
    "        \n",
    "        지침:\n",
    "        1. 한 문장에서 두 문장 정도로 말해 (무조건 맞춤법이 모두 맞을 필요는 없어. 적절히 틀린것도 섞어줘.)\n",
    "        2. 공손하지 마. 커뮤니티 반말이나 편한 말투를 써.\n",
    "        3. 이미지 분석가가 되지 마. 사진 속 사물의 정확한 명칭이나 상태를 구구절절 묘사하면 AI 티가 나니까 절대 금지야.\n",
    "        4. [중요] 설명이나 서론 없이 '댓글 내용'만 출력해.'설명'이나 '감상평'이 아니라 그냥 '커뮤니티 댓글' 한 줄만 출력해.\n",
    "        \"\"\"\n",
    "        \n",
    "        content_parts = [prompt]\n",
    "        \n",
    "        # 이미지 처리 (URL이 있는 경우)\n",
    "        if actual_img_url and actual_img_url.startswith('http'):\n",
    "            try:\n",
    "                img_res = requests.get(actual_img_url, timeout=5)\n",
    "                if img_res.status_code == 200:\n",
    "                    content_parts.append({'mime_type': 'image/jpeg', 'data': img_res.content})\n",
    "            except: pass\n",
    "\n",
    "        try:\n",
    "            # 이미지 포함 시도\n",
    "            response = model.generate_content(content_parts)\n",
    "            ai_comment = response.text.strip()\n",
    "        except Exception:\n",
    "            # 이미지 처리 오류 발생 시 텍스트로만 재시도\n",
    "            response = model.generate_content([prompt])\n",
    "            ai_comment = response.text.strip()\n",
    "\n",
    "        # ---이전 버전---\n",
    "        # if issue['thumbnail'] and issue['thumbnail'].startswith('http'):\n",
    "        #     try:\n",
    "        #         img_data = requests.get(issue['thumbnail']).content\n",
    "        #         content_parts.append({'mime_type': 'image/jpeg', 'data': img_data})\n",
    "        #     except:\n",
    "        #         pass # 이미지 로딩 실패 시 텍스트로만 진행\n",
    "        \n",
    "\n",
    "        # (6) DB에 댓글 삽입\n",
    "        cur.execute(\"\"\"\n",
    "            INSERT INTO public.comments (issue_id, user_id, user_nick, body, created_at)\n",
    "            VALUES (%s, %s, %s, %s, NOW())\n",
    "        \"\"\", (issue['id'], persona['user_id'], persona['nickname'], ai_comment))\n",
    "        \n",
    "        # (7) 댓글 수 카운트 업데이트\n",
    "        cur.execute(\"UPDATE public.issues SET comment_count = comment_count + 1 WHERE id = %s\", (issue['id'],))\n",
    "\n",
    "        conn.commit()\n",
    "        # print(f\"✅ [{persona['nickname']}] : {ai_comment} (조회수 +{new_views})\")\n",
    "        # 현재 시간과 게시글 제목을 포함하여 상세 출력\n",
    "        now = datetime.now().strftime('%H:%M:%S')\n",
    "        print(f\"[{now}] 📌 게시글: {issue['title']}\")\n",
    "        print(f\"         ㄴ 👤 {persona['nickname']}: {ai_comment} (조회수 +{new_views})\")\n",
    "        print(\"-\" * 50)\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"❌ 오류 발생: {e}\")\n",
    "        conn.rollback()\n",
    "    finally:\n",
    "        cur.close()\n",
    "        conn.close()\n",
    "\n",
    "# --- 실행부 ---\n",
    "# 무한 루프 (테스트를 위해 3번만 실행하려면 range(3)으로 수정하세요)\n",
    "print(\"🤖 커뮤니티 자동화 에이전트 가동 시작...\")\n",
    "for _ in range(5): \n",
    "    run_automation_step()\n",
    "    # 비정기적 휴식 (30초~2분 사이 랜덤)\n",
    "    wait = random.randint(600, 7200)\n",
    "    print(f\"💤 {wait}초간 대기 후 다음 활동...\")\n",
    "    time.sleep(wait)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d8429d29-cd6b-48f8-8d5a-2f554419fe62",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
